# base image
FROM node:latest AS build

# set working directory
WORKDIR /app

# Install app dependencies
COPY package*.json /app

RUN npm install
COPY ./ /app
RUN npm run build

# Development
# EXPOSE 3000
# CMD ["npm", "start"]

# Production
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
# RUN mkdir /etc/letsencrypt
# COPY letsencrypt/live/timjose.com/fullchain.pem /etc/letsencrypt
# COPY letsencrypt/live/timjose.com/privkey.pem /etc/letsencrypt
# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.config /etc/nginx/conf.d/default.conf
EXPOSE 80
# EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]