version: '2'
services:
  client:
    image: timsilog/personalwebsite_client:sitefront
    ports:
      - '1337:80'
    depends_on:
      - backend
  backend:
    image: timsilog/personalwebsite_backend:siteback
    ports:
      - '8080:8080'